Famelo:
  MongoDB:
    persistence:
      backendOptions:
        databaseName: 'foo'
        host: 'localhost'
        port: 27017
TYPO3:
  Flow:
    object:
      excludeClasses:
        'Doctrine.MongoDB' : ['.*']
        'doctrine.mongodb-odm' : ['.*']
